name: Gitleaks Scan

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Gitleaks
        run: |
          curl -LO https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64
          chmod +x gitleaks-linux-amd64
          sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks

      - name: Run Gitleaks
        run: gitleaks --config .gitleaks.toml
